const contents = [
  {
    id: 1,
    title: "환생자의 스트리밍",
    author: ["넥스트레벨스튜디오", "흑아인"],
    main: "webtoon",
    sub: "fantasy",
    views: 3317000,
    rating: 9.7,
    day: "sun",
    description: "죽음을 맞이한 헌터가 환생 후 스트리머로 성장하는 이야기.",
    keywords: ["환생", "헌터", "스트리밍"],
    thumbnail: "webtoon_01.webp",
  },
  {
    id: 2,
    title: "악녀의 로맨스는 없다",
    author: ["라엘"],
    main: "webtoon",
    sub: "romance",
    views: 2100000,
    rating: 9.4,
    day: "wed",
    description: "악녀로 빙의했지만 로맨스 대신 자유를 선택한 그녀.",
    keywords: ["로맨스", "빙의"],
    thumbnail: "webtoon_02.jpg",
  },
  {
    id: 3,
    title: "무림에서 온 전학생",
    author: ["천무"],
    main: "webtoon",
    sub: "murim",
    views: 1200000,
    rating: 9.2,
    day: "fri",
    description: "무림 고수가 현대 학교에 전학 오며 벌어지는 이야기.",
    keywords: ["무협", "학원"],
    thumbnail: "webtoon_03.webp",
  },
  {
    id: 4,
    title: "도시의 헌터",
    author: ["박현"],
    main: "webtoon",
    sub: "action",
    views: 980000,
    rating: 9.0,
    day: "thu",
    description: "도시를 위협하는 괴물을 사냥하는 헌터들의 이야기.",
    keywords: ["액션", "헌터"],
    thumbnail: "webtoon_04.webp",
  },
  {
    id: 5,
    title: "귀신 보는 탐정",
    author: ["서윤"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 760000,
    rating: 8.8,
    day: "sat",
    description: "귀신을 볼 수 있는 탐정의 미스터리 사건 해결기.",
    keywords: ["공포", "추리"],
    thumbnail: "webtoon_05.jpg",
  },
  {
    id: 6,
    title: "우리들의 계절",
    author: ["김다은"],
    main: "webtoon",
    sub: "drama",
    views: 640000,
    rating: 8.9,
    day: "mon",
    description: "청춘들의 우정과 사랑을 그린 성장 드라마.",
    keywords: ["드라마", "청춘"],
    thumbnail: "webtoon_06.png",
  },
  {
    id: 7,
    title: "은하계 기사단",
    author: ["이준"],
    main: "webtoon",
    sub: "fantasy",
    views: 880000,
    rating: 9.1,
    day: "tue",
    description: "우주를 지키는 기사단의 SF 판타지 모험.",
    keywords: ["SF", "우주"],
    thumbnail: "webtoon_07.webp",
  },
  {
    id: 8,
    title: "첫사랑 알고리즘",
    author: ["한서"],
    main: "webtoon",
    sub: "romance",
    views: 720000,
    rating: 8.7,
    day: "sun",
    description: "AI로 사랑을 분석하려는 대학생들의 이야기.",
    keywords: ["로맨스", "캠퍼스"],
    thumbnail: "webtoon_08.webp",
  },

  // 웹소설
  {
    id: 9,
    title: "황녀의 계약 결혼",
    author: ["리아"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 2300000,
    rating: 9.6,
    day: null,
    description: "몰락한 황녀와 공작의 계약 결혼 이야기.",
    keywords: ["로판", "계약결혼"],
    thumbnail: "webnovel_01.webp",
  },
  {
    id: 10,
    title: "마나 없는 마법사",
    author: ["하린"],
    main: "webnovel",
    sub: "fantasy",
    views: 870000,
    rating: 9.0,
    day: null,
    description: "마나 없이 지식으로 성장하는 마법사.",
    keywords: ["판타지", "성장"],
    thumbnail: "webnovel_02.webp",
  },
  {
    id: 11,
    title: "그녀의 비밀 연애",
    author: ["소라"],
    main: "webnovel",
    sub: "romance",
    views: 920000,
    rating: 9.2,
    day: null,
    description: "평범한 직장인의 비밀스러운 로맨스.",
    keywords: ["로맨스", "직장"],
    thumbnail: "webnovel_03.jpg",
  },
  {
    id: 12,
    title: "제국의 마지막 기사",
    author: ["도현"],
    main: "webnovel",
    sub: "fantasy",
    views: 680000,
    rating: 8.9,
    day: null,
    description: "멸망한 제국의 마지막 기사가 다시 일어선다.",
    keywords: ["기사", "전쟁"],
    thumbnail: "webnovel_04.jpg",
  },
  {
    id: 13,
    title: "악녀는 오늘도 바쁘다",
    author: ["엘린"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 1100000,
    rating: 9.3,
    day: null,
    description: "악녀로 환생했지만 사업가로 성공하려는 이야기.",
    keywords: ["로판", "환생"],
    thumbnail: "webnovel_05.jpg",
  },
  {
    id: 14,
    title: "랭커가 되었더니 회귀하다.",
    author: ["잠자는 토끼"],
    main: "webnovel",
    sub: "fantasy",
    views: 200000,
    rating: 9.0,
    description: "드디어 게임 랭커가 된 그 순간 레벨 1로 회귀하다.",
    keywords: ["판타지", "회귀", "게임"],
    thumbnail: "webnovel_06.png",
  },
  {
    id: 15,
    title: "탑에 오르다",
    author: ["잠자는 또끼"],
    main: "webnovel",
    sub: "fantasy",
    views: 150000,
    rating: 8.7,
    description: "세상에 나타난 탑에 오르다",
    keywords: ["판타지", "아포칼립스", "던전"],
    thumbnail: "webnovel_07.jpg",
  },
  {
    id: 16,
    title: "던전 요리사",
    author: ["아리엔"],
    main: "webnovel",
    sub: "fantasy",
    views: 180000,
    rating: 8.8,
    description: "던전 요리사로 각성!! 유일무일 던전 요리사가 되다.",
    keywords: ["판타지", "던전"],
    thumbnail: "webnovel_08.jpg",
  },

  // 도서
  {
    id: 17,
    title: "인류의 역사",
    author: ["이정훈"],
    main: "ebook",
    sub: "humanities-social-history",
    views: 150000,
    rating: 8.7,
    description: "인류 문명의 흐름을 쉽게 설명한 역사 교양서.",
    keywords: ["역사"],
    thumbnail: "ebook_01.webp",
  },
  {
    id: 18,
    title: "성공하는 습관",
    author: ["박성민"],
    main: "ebook",
    sub: "self-development",
    views: 180000,
    rating: 8.8,
    description: "성공한 사람들의 습관을 분석한 자기계발서.",
    keywords: ["습관"],
    thumbnail: "ebook_02.webp",
  },
  {
    id: 19,
    title: "경영의 기술",
    author: ["최강"],
    main: "ebook",
    sub: "business-economy",
    views: 120000,
    rating: 8.5,
    description: "현대 기업 경영 전략을 설명한 책.",
    keywords: ["경영"],
    thumbnail: "ebook_03.webp",
  },
  {
    id: 20,
    title: "조용한 시",
    author: ["김하늘"],
    main: "ebook",
    sub: "essay-poetry",
    views: 80000,
    rating: 8.6,
    description: "삶의 감정을 담은 시와 에세이 모음.",
    keywords: ["에세이", "시"],
    thumbnail: "ebook_04.jpg",
  },
  {
    id: 21,
    title: "도시의 철학",
    author: ["이상우"],
    main: "ebook",
    sub: "humanities-social-history",
    views: 90000,
    rating: 8.4,
    description: "도시 속 인간의 삶을 철학적으로 탐구한다.",
    keywords: ["철학"],
    thumbnail: "ebook_05.jpg",
  },
  {
    id: 22,
    title: "문학의 순간",
    author: ["정유진"],
    main: "ebook",
    sub: "novel",
    views: 130000,
    rating: 8.7,
    description: "인간 관계와 삶을 그린 현대 소설.",
    keywords: ["소설"],
    thumbnail: "ebook_06.webp",
  },
  {
    id: 23,
    title: "별이 빛나는 밤에",
    author: ["김하늘"],
    main: "ebook",
    sub: "novel",
    views: 98000,
    rating: 8.5,
    description: "청춘의 고민과 사랑을 담은 감성적인 성장 소설.",
    keywords: ["소설", "청춘", "성장"],
    thumbnail: "ebook_07.webp",
  },
  {
    id: 24,
    title: "시간의 서재",
    author: ["박민준"],
    main: "ebook",
    sub: "novel",
    views: 112000,
    rating: 9.0,
    description: "오래된 도서관에서 펼쳐지는 미스터리한 이야기.",
    keywords: ["미스터리", "소설"],
    thumbnail: "ebook_08.webp",
  },
  {
    id: 25,
    title: "검왕의 귀환",
    author: ["강태성"],
    main: "webtoon",
    sub: "murim",
    views: 540000,
    rating: 9.1,
    day: "mon",
    description: "전설의 검왕이 현대에 다시 돌아왔다.",
    keywords: ["무협", "환생"],
    thumbnail: "webtoon_09.webp",
  },
  {
    id: 26,
    title: "AI 연인",
    author: ["유리"],
    main: "webtoon",
    sub: "romance",
    views: 430000,
    rating: 8.8,
    day: "tue",
    description: "AI와 사랑에 빠진 개발자의 이야기.",
    keywords: ["로맨스", "AI"],
    thumbnail: "webtoon_10.webp",
  },
  {
    id: 27,
    title: "아포칼립스 생존자",
    author: ["정민"],
    main: "webtoon",
    sub: "action",
    views: 620000,
    rating: 9.0,
    day: "fri",
    description: "멸망한 세상에서 살아남은 사람들의 이야기.",
    keywords: ["액션", "아포칼립스"],
    thumbnail: "webtoon_01.webp",
  },
  {
    id: 28,
    title: "마왕의 딸",
    author: ["엘라"],
    main: "webtoon",
    sub: "fantasy",
    views: 700000,
    rating: 9.3,
    day: "sun",
    description: "마왕의 딸이 인간 세계에서 살아가는 이야기.",
    keywords: ["판타지", "마왕"],
    thumbnail: "webtoon_03.webp",
  },
  {
    id: 29,
    title: "도시 괴담 수집가",
    author: ["이도"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 380000,
    rating: 8.6,
    day: "sat",
    description: "도시 괴담을 수집하는 기자의 이야기.",
    keywords: ["공포", "괴담"],
    thumbnail: "webtoon_04.webp",
  },
  {
    id: 30,
    title: "황제의 숨겨진 후계자",
    author: ["카린"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 760000,
    rating: 9.1,
    description: "숨겨진 황제의 후계자가 궁에 들어오면서 벌어지는 이야기.",
    keywords: ["로판", "궁중"],
    thumbnail: "webnovel_09.webp",
  },
  {
    id: 31,
    title: "던전 마스터의 귀환",
    author: ["이준혁"],
    main: "webnovel",
    sub: "fantasy",
    views: 540000,
    rating: 8.9,
    description: "던전 마스터가 다시 세상에 돌아왔다.",
    keywords: ["던전", "환생"],
    thumbnail: "webnovel_10.png",
  },
  {
    id: 32,
    title: "사랑은 알고리즘처럼",
    author: ["민서"],
    main: "webnovel",
    sub: "romance",
    views: 420000,
    rating: 8.7,
    description: "완벽한 사랑을 찾는 데이터 분석가의 이야기.",
    keywords: ["로맨스", "연애"],
    thumbnail: "webnovel_01.webp",
  },
  {
    id: 33,
    title: "왕국의 마법사",
    author: ["도윤"],
    main: "webnovel",
    sub: "fantasy",
    views: 390000,
    rating: 8.8,
    description: "왕국을 지키는 젊은 마법사의 성장기.",
    keywords: ["마법", "성장"],
    thumbnail: "webnovel_03.jpg",
  },
  {
    id: 34,
    title: "악역은 오늘도 살아남는다",
    author: ["리아나"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 610000,
    rating: 9.2,
    description: "소설 속 악역으로 빙의한 여자의 생존기.",
    keywords: ["빙의", "로판"],
    thumbnail: "webnovel_08.jpg",
  },
  {
    id: 35,
    title: "철학자의 하루",
    author: ["박준"],
    main: "ebook",
    sub: "humanities-social-history",
    views: 45000,
    rating: 8.5,
    description: "철학자의 시선으로 바라본 하루의 의미.",
    keywords: ["철학"],
    thumbnail: "ebook_09.png",
  },
  {
    id: 36,
    title: "경제의 흐름",
    author: ["김민수"],
    main: "ebook",
    sub: "business-economy",
    views: 72000,
    rating: 8.6,
    description: "현대 경제의 흐름을 쉽게 설명한다.",
    keywords: ["경제"],
    thumbnail: "ebook_10.webp",
  },
  {
    id: 37,
    title: "마음의 기록",
    author: ["이서연"],
    main: "ebook",
    sub: "essay-poetry",
    views: 38000,
    rating: 8.4,
    description: "삶의 감정을 기록한 에세이 모음.",
    keywords: ["에세이"],
    thumbnail: "ebook_01.webp",
  },
  {
    id: 38,
    title: "성장의 기술",
    author: ["정우"],
    main: "ebook",
    sub: "self-development",
    views: 91000,
    rating: 8.9,
    description: "자기 성장을 위한 실천 전략.",
    keywords: ["자기계발"],
    thumbnail: "ebook_04.jpg",
  },
  {
    id: 39,
    title: "밤의 도서관",
    author: ["김하늘"],
    main: "ebook",
    sub: "novel",
    views: 56000,
    rating: 8.7,
    description: "밤이 되면 살아나는 도서관 이야기.",
    keywords: ["소설", "미스터리"],
    thumbnail: "ebook_03.webp",
  },
  {
    id: 40,
    title: "사라진 왕국",
    author: ["최민"],
    main: "ebook",
    sub: "novel",
    views: 62000,
    rating: 8.6,
    description: "사라진 왕국의 비밀을 찾는 모험 소설.",
    keywords: ["모험", "소설"],
    thumbnail: "ebook_06.webp",
  },
  {
    id: 41,
    title: "세계사 산책",
    author: ["이정훈"],
    main: "ebook",
    sub: "humanities-social-history",
    views: 84000,
    rating: 8.8,
    description: "세계사를 흥미롭게 풀어낸 역사 교양서.",
    keywords: ["세계사"],
    thumbnail: "ebook_07.webp",
  },
  {
    id: 42,
    title: "부자의 사고방식",
    author: ["김도현"],
    main: "ebook",
    sub: "business-economy",
    views: 97000,
    rating: 9.0,
    description: "성공한 사람들의 사고방식을 분석한다.",
    keywords: ["경제", "성공"],
    thumbnail: "ebook_08.webp",
  },
  {
    id: 43,
    title: "감정의 온도",
    author: ["서지안"],
    main: "ebook",
    sub: "essay-poetry",
    views: 41000,
    rating: 8.5,
    description: "일상 속 감정을 담은 에세이.",
    keywords: ["감정", "에세이"],
    thumbnail: "ebook_10.webp",
  },
  {
    id: 44,
    title: "내일을 준비하는 법",
    author: ["이수진"],
    main: "ebook",
    sub: "self-development",
    views: 66000,
    rating: 8.8,
    description: "미래를 준비하는 사람들을 위한 자기계발서.",
    keywords: ["자기계발"],
    thumbnail: "ebook_01.webp",
  },
  {
    id: 45,
    title: "던전 청소부",
    author: ["김태훈"],
    main: "webtoon",
    sub: "action",
    views: 420000,
    rating: 8.9,
    day: "mon",
    description: "던전이 끝난 뒤 몬스터 잔해를 치우는 청소부의 이야기.",
    keywords: ["던전", "헌터"],
    thumbnail: "webtoon_08.webp",
  },
  {
    id: 46,
    title: "마법학교 낙제생",
    author: ["한지우"],
    main: "webtoon",
    sub: "fantasy",
    views: 510000,
    rating: 9.0,
    day: "tue",
    description: "마법을 못 쓰는 학생이 마법학교에서 살아남는 이야기.",
    keywords: ["마법", "학원"],
    thumbnail: "webtoon_09.webp",
  },
  {
    id: 47,
    title: "그녀의 이중생활",
    author: ["서연"],
    main: "webtoon",
    sub: "drama",
    views: 370000,
    rating: 8.7,
    day: "wed",
    description: "낮에는 회사원, 밤에는 인기 스트리머인 그녀의 이야기.",
    keywords: ["드라마", "일상"],
    thumbnail: "webtoon_10.webp",
  },
  {
    id: 48,
    title: "첫사랑 리셋",
    author: ["이민재"],
    main: "webtoon",
    sub: "romance",
    views: 600000,
    rating: 9.2,
    day: "thu",
    description: "첫사랑과 다시 만난 두 사람의 리셋된 로맨스.",
    keywords: ["로맨스", "재회"],
    thumbnail: "webtoon_04.webp",
  },
  {
    id: 49,
    title: "귀신 아파트",
    author: ["박소영"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 330000,
    rating: 8.5,
    day: "fri",
    description: "귀신이 산다는 아파트에서 벌어지는 미스터리.",
    keywords: ["공포", "괴담"],
    thumbnail: "webtoon_08.webp",
  },
  {
    id: 50,
    title: "무림 편의점",
    author: ["천무"],
    main: "webtoon",
    sub: "murim",
    views: 470000,
    rating: 9.1,
    day: "sat",
    description: "무림 고수들이 찾는 특별한 편의점 이야기.",
    keywords: ["무협", "코믹"],
    thumbnail: "webtoon_02.jpg",
  },
  {
    id: 51,
    title: "우주 택배",
    author: ["정하늘"],
    main: "webtoon",
    sub: "fantasy",
    views: 390000,
    rating: 8.8,
    day: "sun",
    description: "우주를 누비는 택배기사의 SF 모험.",
    keywords: ["SF", "모험"],
    thumbnail: "webtoon_06.png",
  },
  {
    id: 52,
    title: "연애 시뮬레이션",
    author: ["김지훈"],
    main: "webtoon",
    sub: "romance",
    views: 450000,
    rating: 8.9,
    day: "mon",
    description: "게임처럼 연애를 분석하는 대학생들의 이야기.",
    keywords: ["로맨스", "캠퍼스"],
    thumbnail: "webtoon_03.webp",
  },
  {
    id: 53,
    title: "헌터 랭킹 1위",
    author: ["이강"],
    main: "webtoon",
    sub: "action",
    views: 680000,
    rating: 9.3,
    day: "wed",
    description: "세계 최고의 헌터가 되는 과정을 그린 액션 웹툰.",
    keywords: ["헌터", "액션"],
    thumbnail: "webtoon_06.png",
  },
  {
    id: 54,
    title: "시간을 걷는 소녀",
    author: ["최윤"],
    main: "webtoon",
    sub: "drama",
    views: 310000,
    rating: 8.6,
    day: "thu",
    description: "시간을 되돌릴 수 있는 소녀의 성장 이야기.",
    keywords: ["시간", "성장"],
    thumbnail: "webtoon_05.jpg",
  },
  {
    id: 55,
    title: "계약 연애의 시작",
    author: ["유나"],
    main: "webtoon",
    sub: "romance",
    views: 510000,
    rating: 9.1,
    day: "mon",
    description: "가짜 연애로 시작된 두 사람의 이야기.",
    keywords: ["로맨스", "계약연애"],
    thumbnail: "webtoon_11.jpg",
  },
  {
    id: 56,
    title: "첫사랑 리턴",
    author: ["민서"],
    main: "webtoon",
    sub: "romance",
    views: 430000,
    rating: 8.9,
    day: "tue",
    description: "10년 뒤 다시 만난 첫사랑.",
    keywords: ["첫사랑"],
    thumbnail: "webtoon_12.jpg",
  },
  {
    id: 57,
    title: "비밀 연애",
    author: ["서하"],
    main: "webtoon",
    sub: "romance",
    views: 390000,
    rating: 8.7,
    day: "wed",
    description: "회사에서 시작된 비밀 연애.",
    keywords: ["직장"],
    thumbnail: "webtoon_13.jpg",
  },
  {
    id: 58,
    title: "연애 알고리즘",
    author: ["지훈"],
    main: "webtoon",
    sub: "romance",
    views: 470000,
    rating: 9.0,
    day: "thu",
    description: "사랑을 계산하는 프로그램.",
    keywords: ["AI"],
    thumbnail: "webtoon_07.webp",
  },
  {
    id: 59,
    title: "고백 연습",
    author: ["유리"],
    main: "webtoon",
    sub: "romance",
    views: 350000,
    rating: 8.6,
    day: "fri",
    description: "고백 연습을 하다 사랑에 빠지다.",
    keywords: ["고백"],
    thumbnail: "webtoon_15.png",
  },
  {
    id: 60,
    title: "AI 여자친구",
    author: ["민재"],
    main: "webtoon",
    sub: "romance",
    views: 420000,
    rating: 8.8,
    day: "sat",
    description: "AI와 사랑에 빠진 개발자.",
    keywords: ["AI"],
    thumbnail: "webtoon_14.jpg",
  },
  {
    id: 61,
    title: "그녀의 비밀",
    author: ["수아"],
    main: "webtoon",
    sub: "romance",
    views: 370000,
    rating: 8.7,
    day: "sun",
    description: "완벽한 그녀의 숨겨진 비밀.",
    keywords: ["비밀"],
    thumbnail: "webtoon_17.jpg",
  },
  {
    id: 62,
    title: "우리의 여름",
    author: ["태준"],
    main: "webtoon",
    sub: "romance",
    views: 410000,
    rating: 8.9,
    day: "mon",
    description: "여름에 시작된 청춘 로맨스.",
    keywords: ["청춘"],
    thumbnail: "webtoon_18.webp",
  },
  {
    id: 63,
    title: "운명적인 만남",
    author: ["도윤"],
    main: "webtoon",
    sub: "romance",
    views: 520000,
    rating: 9.2,
    day: "tue",
    description: "우연처럼 시작된 사랑.",
    keywords: ["운명"],
    thumbnail: "webtoon_19.png",
  },
  {
    id: 64,
    title: "사랑의 타이밍",
    author: ["하린"],
    main: "webtoon",
    sub: "romance",
    views: 330000,
    rating: 8.6,
    day: "wed",
    description: "타이밍이 엇갈린 두 사람.",
    keywords: ["재회"],
    thumbnail: "webtoon_20.jpg",
  },
  {
    id: 65,
    title: "마법사의 제자",
    author: ["윤호"],
    main: "webtoon",
    sub: "fantasy",
    views: 610000,
    rating: 9.2,
    day: "thu",
    description: "전설의 마법사의 제자가 된 소년.",
    keywords: ["마법"],
    thumbnail: "webtoon_21.jpg",
  },
  {
    id: 66,
    title: "드래곤 헌터",
    author: ["민수"],
    main: "webtoon",
    sub: "fantasy",
    views: 580000,
    rating: 9.1,
    day: "fri",
    description: "드래곤을 사냥하는 헌터.",
    keywords: ["드래곤"],
    thumbnail: "webtoon_20.jpg",
  },
  {
    id: 67,
    title: "마왕의 귀환",
    author: ["지훈"],
    main: "webtoon",
    sub: "fantasy",
    views: 640000,
    rating: 9.3,
    day: "sat",
    description: "마왕이 인간 세계로 돌아왔다.",
    keywords: ["마왕"],
    thumbnail: "webtoon_22.jpg",
  },
  {
    id: 68,
    title: "용사의 후계자",
    author: ["하린"],
    main: "webtoon",
    sub: "fantasy",
    views: 520000,
    rating: 9.0,
    day: "sun",
    description: "용사의 피를 이은 소년.",
    keywords: ["용사"],
    thumbnail: "webtoon_11.jpg",
  },
  {
    id: 69,
    title: "마나 없는 마법사",
    author: ["수민"],
    main: "webtoon",
    sub: "fantasy",
    views: 480000,
    rating: 8.9,
    day: "mon",
    description: "마나 없이 성장하는 마법사.",
    keywords: ["성장"],
    thumbnail: "webtoon_12.jpg",
  },
  {
    id: 70,
    title: "차원 여행자",
    author: ["태호"],
    main: "webtoon",
    sub: "fantasy",
    views: 460000,
    rating: 8.8,
    day: "tue",
    description: "차원을 넘나드는 여행.",
    keywords: ["차원"],
    thumbnail: "webtoon_13.jpg",
  },
  {
    id: 71,
    title: "엘프 왕국",
    author: ["민아"],
    main: "webtoon",
    sub: "fantasy",
    views: 410000,
    rating: 8.8,
    day: "wed",
    description: "엘프 왕국의 전쟁.",
    keywords: ["엘프"],
    thumbnail: "webtoon_14.jpg",
  },
  {
    id: 72,
    title: "마법 도시",
    author: ["지연"],
    main: "webtoon",
    sub: "fantasy",
    views: 420000,
    rating: 8.7,
    day: "thu",
    description: "마법이 일상이 된 도시.",
    keywords: ["도시"],
    thumbnail: "webtoon_15.png",
  },
  {
    id: 73,
    title: "왕국의 기사",
    author: ["성준"],
    main: "webtoon",
    sub: "fantasy",
    views: 500000,
    rating: 9.0,
    day: "fri",
    description: "왕국을 지키는 기사.",
    keywords: ["기사"],
    thumbnail: "webtoon_16.png",
  },
  {
    id: 74,
    title: "마법 학교",
    author: ["지수"],
    main: "webtoon",
    sub: "fantasy",
    views: 450000,
    rating: 8.9,
    day: "sat",
    description: "마법 학교에서 벌어지는 이야기.",
    keywords: ["학원"],
    thumbnail: "webtoon_17.jpg",
  },
  {
    id: 75,
    title: "검왕의 귀환",
    author: ["강태성"],
    main: "webtoon",
    sub: "murim",
    views: 540000,
    rating: 9.1,
    day: "mon",
    description: "전설의 검왕이 현대에 돌아왔다.",
    keywords: ["무협", "환생"],
    thumbnail: "webtoon_18.webp",
  },
  {
    id: 76,
    title: "무림 편의점",
    author: ["천무"],
    main: "webtoon",
    sub: "murim",
    views: 470000,
    rating: 9.1,
    day: "sat",
    description: "무림 고수들이 찾는 특별한 편의점 이야기.",
    keywords: ["무협", "코믹"],
    thumbnail: "webtoon_19.png",
  },
  {
    id: 77,
    title: "강호의 전설",
    author: ["도윤"],
    main: "webtoon",
    sub: "murim",
    views: 500000,
    rating: 9.0,
    day: "sun",
    description: "강호에서 벌어지는 전설적인 무협 이야기.",
    keywords: ["무협", "전설"],
    thumbnail: "webtoon_20.jpg",
  },
  {
    id: 78,
    title: "천하제일검",
    author: ["하린"],
    main: "webtoon",
    sub: "murim",
    views: 430000,
    rating: 8.8,
    day: "mon",
    description: "천하제일검을 찾기 위한 여정.",
    keywords: ["검", "무협"],
    thumbnail: "webtoon_21.jpg",
  },
  {
    id: 79,
    title: "무림 고수 일기",
    author: ["이준"],
    main: "webtoon",
    sub: "murim",
    views: 390000,
    rating: 8.7,
    day: "tue",
    description: "무림 고수의 일상과 모험.",
    keywords: ["무협", "일상"],
    thumbnail: "webtoon_22.jpg",
  },
  {
    id: 80,
    title: "검의 후예",
    author: ["민서"],
    main: "webtoon",
    sub: "murim",
    views: 420000,
    rating: 8.9,
    day: "wed",
    description: "검술의 후예가 되어 세상을 구하는 이야기.",
    keywords: ["무협", "검술"],
    thumbnail: "webtoon_01.webp",
  },
  {
    id: 81,
    title: "혈검",
    author: ["지훈"],
    main: "webtoon",
    sub: "murim",
    views: 410000,
    rating: 8.8,
    day: "thu",
    description: "강호에 나타난 피의 검 이야기.",
    keywords: ["무협", "검"],
    thumbnail: "webtoon_16.png",
  },
  {
    id: 82,
    title: "무림 영웅전",
    author: ["수아"],
    main: "webtoon",
    sub: "murim",
    views: 450000,
    rating: 9.0,
    day: "fri",
    description: "영웅이 된 무림인의 전설.",
    keywords: ["무협", "영웅"],
    thumbnail: "webtoon_06.png",
  },
  {
    id: 83,
    title: "강호의 선택",
    author: ["태준"],
    main: "webtoon",
    sub: "murim",
    views: 430000,
    rating: 8.9,
    day: "sat",
    description: "강호에서 올바른 선택을 하는 이야기.",
    keywords: ["무협", "선택"],
    thumbnail: "webtoon_17.jpg",
  },
  {
    id: 84,
    title: "검과 그림자",
    author: ["하늘"],
    main: "webtoon",
    sub: "murim",
    views: 400000,
    rating: 8.7,
    day: "sun",
    description: "검과 그림자가 엮이는 무협 스토리.",
    keywords: ["무협", "그림자"],
    thumbnail: "webtoon_18.webp",
  },
  {
    id: 85,
    title: "아포칼립스 생존자",
    author: ["정민"],
    main: "webtoon",
    sub: "action",
    views: 620000,
    rating: 9.0,
    day: "fri",
    description: "멸망한 세상에서 살아남은 이야기.",
    keywords: ["액션", "아포칼립스"],
    thumbnail: "webtoon_11.jpg",
  },
  {
    id: 86,
    title: "헌터 랭킹 1위",
    author: ["이강"],
    main: "webtoon",
    sub: "action",
    views: 680000,
    rating: 9.3,
    day: "wed",
    description: "세계 최고의 헌터 이야기.",
    keywords: ["헌터", "액션"],
    thumbnail: "webtoon_12.jpg",
  },
  {
    id: 87,
    title: "도시 히어로",
    author: ["민재"],
    main: "webtoon",
    sub: "action",
    views: 550000,
    rating: 9.0,
    day: "thu",
    description: "도시를 지키는 히어로의 이야기.",
    keywords: ["액션", "히어로"],
    thumbnail: "webtoon_13.jpg",
  },
  {
    id: 88,
    title: "레전드 파이터",
    author: ["지훈"],
    main: "webtoon",
    sub: "action",
    views: 500000,
    rating: 8.8,
    day: "mon",
    description: "최강 파이터들의 대결.",
    keywords: ["격투", "액션"],
    thumbnail: "webtoon_14.jpg",
  },
  {
    id: 89,
    title: "비밀 특수부대",
    author: ["수아"],
    main: "webtoon",
    sub: "action",
    views: 480000,
    rating: 8.9,
    day: "tue",
    description: "비밀 특수부대의 활약.",
    keywords: ["액션", "군사"],
    thumbnail: "webtoon_15.png",
  },
  {
    id: 90,
    title: "폭주 히어로",
    author: ["태호"],
    main: "webtoon",
    sub: "action",
    views: 470000,
    rating: 8.7,
    day: "wed",
    description: "억울한 복수를 위한 폭주 히어로.",
    keywords: ["액션", "복수"],
    thumbnail: "webtoon_16.png",
  },
  {
    id: 91,
    title: "미래 전사",
    author: ["하린"],
    main: "webtoon",
    sub: "action",
    views: 450000,
    rating: 8.8,
    day: "thu",
    description: "미래에서 온 전사의 액션 스토리.",
    keywords: ["액션", "SF"],
    thumbnail: "webtoon_19.png",
  },
  {
    id: 92,
    title: "도시의 헌터",
    author: ["박현"],
    main: "webtoon",
    sub: "action",
    views: 490000,
    rating: 9.0,
    day: "thu",
    description: "도시를 위협하는 괴물을 사냥하는 헌터.",
    keywords: ["액션", "헌터"],
    thumbnail: "webtoon_18.webp",
  },
  {
    id: 93,
    title: "암살자 길드",
    author: ["지연"],
    main: "webtoon",
    sub: "action",
    views: 460000,
    rating: 8.9,
    day: "fri",
    description: "비밀 암살자 길드의 이야기.",
    keywords: ["액션", "암살"],
    thumbnail: "webtoon_17.jpg",
  },
  {
    id: 94,
    title: "생존 게임",
    author: ["민아"],
    main: "webtoon",
    sub: "action",
    views: 440000,
    rating: 8.7,
    day: "sat",
    description: "극한 생존 게임 속 액션 모험.",
    keywords: ["액션", "서바이벌"],
    thumbnail: "webtoon_20.jpg",
  },
  {
    id: 95,
    title: "귀신 아파트",
    author: ["박소영"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 330000,
    rating: 8.5,
    day: "fri",
    description: "귀신이 산다는 아파트에서 벌어지는 이야기.",
    keywords: ["공포", "괴담"],
    thumbnail: "webtoon_21.jpg",
  },
  {
    id: 96,
    title: "귀신 보는 탐정",
    author: ["서윤"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 760000,
    rating: 8.8,
    day: "sat",
    description: "귀신을 볼 수 있는 탐정의 미스터리 사건 해결기.",
    keywords: ["공포", "추리"],
    thumbnail: "webtoon_22.jpg",
  },
  {
    id: 97,
    title: "밤의 학교",
    author: ["이도"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 320000,
    rating: 8.6,
    day: "sun",
    description: "밤마다 괴현상이 일어나는 학교.",
    keywords: ["공포", "학교"],
    thumbnail: "webtoon_05.jpg",
  },
  {
    id: 98,
    title: "유령 열차",
    author: ["지훈"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 310000,
    rating: 8.5,
    day: "mon",
    description: "밤마다 운행하는 유령 열차.",
    keywords: ["공포", "열차"],
    thumbnail: "webtoon_17.jpg",
  },
  {
    id: 99,
    title: "폐가 탐험",
    author: ["민서"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 300000,
    rating: 8.4,
    day: "tue",
    description: "폐가에서 벌어지는 공포 이야기.",
    keywords: ["공포", "탐험"],
    thumbnail: "webtoon_11.jpg",
  },
  {
    id: 100,
    title: "미스터리 호텔",
    author: ["수아"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 290000,
    rating: 8.3,
    day: "wed",
    description: "호텔에서 발생하는 미스터리 사건.",
    keywords: ["공포", "호텔"],
    thumbnail: "webtoon_20.jpg",
  },
  {
    id: 101,
    title: "악몽의 숲",
    author: ["태준"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 280000,
    rating: 8.4,
    day: "thu",
    description: "악몽처럼 펼쳐지는 숲의 이야기.",
    keywords: ["공포", "숲"],
    thumbnail: "webtoon_13.jpg",
  },
  {
    id: 102,
    title: "저주받은 마을",
    author: ["지연"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 270000,
    rating: 8.5,
    day: "fri",
    description: "저주받은 마을에서 벌어지는 사건.",
    keywords: ["공포", "마을"],
    thumbnail: "webtoon_12.jpg",
  },
  {
    id: 103,
    title: "유령의 집",
    author: ["민아"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 260000,
    rating: 8.3,
    day: "sat",
    description: "유령이 나타나는 오래된 집.",
    keywords: ["공포", "집"],
    thumbnail: "webtoon_14.jpg",
  },
  {
    id: 104,
    title: "심령 카페",
    author: ["지훈"],
    main: "webtoon",
    sub: "horror-mystery",
    views: 250000,
    rating: 8.2,
    day: "sun",
    description: "심령 현상이 일어나는 카페.",
    keywords: ["공포", "카페"],
    thumbnail: "webtoon_18.webp",
  },
  {
    id: 105,
    title: "우리들의 계절",
    author: ["김다은"],
    main: "webtoon",
    sub: "drama",
    views: 640000,
    rating: 8.9,
    day: "mon",
    description: "청춘들의 우정과 사랑을 그린 성장 드라마.",
    keywords: ["드라마", "청춘"],
    thumbnail: "webtoon_01.webp",
  },
  {
    id: 106,
    title: "시간을 걷는 소녀",
    author: ["최윤"],
    main: "webtoon",
    sub: "drama",
    views: 310000,
    rating: 8.6,
    day: "thu",
    description: "시간을 되돌릴 수 있는 소녀의 성장 이야기.",
    keywords: ["시간", "성장"],
    thumbnail: "webtoon_18.webp",
  },
  {
    id: 107,
    title: "그녀의 이중생활",
    author: ["서연"],
    main: "webtoon",
    sub: "drama",
    views: 370000,
    rating: 8.7,
    day: "wed",
    description: "낮에는 회사원, 밤에는 인기 스트리머인 그녀.",
    keywords: ["드라마", "일상"],
    thumbnail: "webtoon_11.jpg",
  },
  {
    id: 108,
    title: "청춘 일기",
    author: ["태준"],
    main: "webtoon",
    sub: "drama",
    views: 400000,
    rating: 8.8,
    day: "fri",
    description: "청춘들의 사랑과 우정 이야기.",
    keywords: ["청춘", "드라마"],
    thumbnail: "webtoon_15.png",
  },
  {
    id: 109,
    title: "꿈꾸는 나날",
    author: ["하린"],
    main: "webtoon",
    sub: "drama",
    views: 380000,
    rating: 8.7,
    day: "sat",
    description: "꿈을 향해 달리는 청춘들의 이야기.",
    keywords: ["드라마", "성장"],
    thumbnail: "webtoon_12.jpg",
  },
  {
    id: 110,
    title: "우리 집 이야기",
    author: ["민서"],
    main: "webtoon",
    sub: "drama",
    views: 350000,
    rating: 8.6,
    day: "sun",
    description: "가족과 함께 살아가는 이야기.",
    keywords: ["드라마", "가족"],
    thumbnail: "webtoon_13.jpg",
  },
  {
    id: 111,
    title: "사랑의 계절",
    author: ["지훈"],
    main: "webtoon",
    sub: "drama",
    views: 360000,
    rating: 8.7,
    day: "mon",
    description: "계절마다 변하는 사랑 이야기.",
    keywords: ["드라마", "로맨스"],
    thumbnail: "webtoon_19.png",
  },
  {
    id: 112,
    title: "청춘을 그리다",
    author: ["수아"],
    main: "webtoon",
    sub: "drama",
    views: 340000,
    rating: 8.5,
    day: "tue",
    description: "청춘들의 고민과 성장 이야기.",
    keywords: ["청춘", "드라마"],
    thumbnail: "webtoon_21.jpg",
  },
  {
    id: 113,
    title: "마지막 여름",
    author: ["민아"],
    main: "webtoon",
    sub: "drama",
    views: 330000,
    rating: 8.4,
    day: "wed",
    description: "청춘들의 마지막 여름 이야기.",
    keywords: ["청춘", "여름"],
    thumbnail: "webtoon_17.jpg",
  },
  {
    id: 114,
    title: "청춘의 기록",
    author: ["지연"],
    main: "webtoon",
    sub: "drama",
    views: 320000,
    rating: 8.3,
    day: "thu",
    description: "청춘의 감정을 담은 성장 이야기.",
    keywords: ["청춘", "드라마"],
    thumbnail: "webtoon_08.webp",
  },
  {
    id: 115,
    title: "사랑의 조건",
    author: ["리아"],
    main: "webnovel",
    sub: "romance",
    views: 320000,
    rating: 9.0,
    description: "서로 다른 배경의 두 사람의 로맨스.",
    keywords: ["로맨스", "계약"],
    thumbnail: "webnovel_11.jpg",
  },
  {
    id: 116,
    title: "첫사랑 리셋",
    author: ["하린"],
    main: "webnovel",
    sub: "romance",
    views: 280000,
    rating: 8.8,
    description: "첫사랑과 다시 시작하는 이야기.",
    keywords: ["첫사랑"],
    thumbnail: "webnovel_06.png",
  },
  {
    id: 117,
    title: "비밀 연애",
    author: ["소라"],
    main: "webnovel",
    sub: "romance",
    views: 250000,
    rating: 8.7,
    description: "직장에서 벌어지는 비밀 연애.",
    keywords: ["직장", "비밀"],
    thumbnail: "webnovel_19.jpg",
  },
  {
    id: 118,
    title: "그녀의 하루",
    author: ["지은"],
    main: "webnovel",
    sub: "romance",
    views: 270000,
    rating: 8.9,
    description: "평범한 일상 속 두 사람의 사랑.",
    keywords: ["일상", "로맨스"],
    thumbnail: "webnovel_12.png",
  },
  {
    id: 119,
    title: "연애 알고리즘",
    author: ["민재"],
    main: "webnovel",
    sub: "romance",
    views: 300000,
    rating: 9.1,
    description: "AI로 연애를 분석하는 대학생들.",
    keywords: ["AI", "연애"],
    thumbnail: "webnovel_17.png",
  },
  {
    id: 120,
    title: "고백 연습",
    author: ["유리"],
    main: "webnovel",
    sub: "romance",
    views: 240000,
    rating: 8.6,
    description: "고백 연습하다 사랑을 찾다.",
    keywords: ["고백"],
    thumbnail: "webnovel_08.jpg",
  },
  {
    id: 121,
    title: "우연한 만남",
    author: ["도윤"],
    main: "webnovel",
    sub: "romance",
    views: 310000,
    rating: 9.0,
    description: "우연히 만난 두 사람의 이야기.",
    keywords: ["우연", "로맨스"],
    thumbnail: "webnovel_10.png",
  },
  {
    id: 122,
    title: "사랑의 선택",
    author: ["하린"],
    main: "webnovel",
    sub: "romance",
    views: 260000,
    rating: 8.7,
    description: "사랑 앞에서 내리는 선택.",
    keywords: ["선택", "로맨스"],
    thumbnail: "webnovel_14.webp",
  },
  {
    id: 123,
    title: "연애 일기",
    author: ["지연"],
    main: "webnovel",
    sub: "romance",
    views: 280000,
    rating: 8.8,
    description: "일기를 통해 시작되는 사랑.",
    keywords: ["일기", "로맨스"],
    thumbnail: "webnovel_16.webp",
  },
  {
    id: 124,
    title: "계절의 사랑",
    author: ["수아"],
    main: "webnovel",
    sub: "romance",
    views: 290000,
    rating: 8.9,
    description: "계절마다 변하는 사랑 이야기.",
    keywords: ["계절", "로맨스"],
    thumbnail: "webnovel_09.webp",
  },
  {
    id: 125,
    title: "황녀의 계약",
    author: ["리아"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 410000,
    rating: 9.2,
    description: "몰락 황녀와 공작의 계약 결혼 이야기.",
    keywords: ["로판", "계약"],
    thumbnail: "webnovel_18.png",
  },
  {
    id: 126,
    title: "악녀는 오늘도 바쁘다",
    author: ["엘린"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 380000,
    rating: 9.0,
    description: "악녀로 환생했지만 성공하려는 이야기.",
    keywords: ["로판", "환생"],
    thumbnail: "webnovel_17.png",
  },
  {
    id: 127,
    title: "황제의 사랑",
    author: ["하린"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 360000,
    rating: 8.9,
    description: "황제와 공주의 금지된 사랑.",
    keywords: ["로판", "황제"],
    thumbnail: "webnovel_11.jpg",
  },
  {
    id: 128,
    title: "마법 왕국의 연인",
    author: ["지은"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 340000,
    rating: 8.8,
    description: "마법 왕국에서 펼쳐지는 로맨스 판타지.",
    keywords: ["로판", "마법"],
    thumbnail: "webnovel_15.jpg",
  },
  {
    id: 129,
    title: "계약 황녀",
    author: ["민서"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 330000,
    rating: 8.7,
    description: "황녀와 공작의 결혼 계약 이야기.",
    keywords: ["로판", "황녀"],
    thumbnail: "webnovel_19.jpg",
  },
  {
    id: 130,
    title: "마법과 사랑",
    author: ["지훈"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 310000,
    rating: 8.8,
    description: "마법과 사랑이 얽힌 이야기.",
    keywords: ["로판", "마법"],
    thumbnail: "webnovel_12.png",
  },
  {
    id: 131,
    title: "황제와 계약",
    author: ["수아"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 300000,
    rating: 8.7,
    description: "황제와 계약 결혼을 한 이야기.",
    keywords: ["로판", "황제"],
    thumbnail: "webnovel_06.png",
  },
  {
    id: 132,
    title: "마법 황녀",
    author: ["태준"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 290000,
    rating: 8.6,
    description: "마법 황녀의 성장과 사랑 이야기.",
    keywords: ["로판", "마법"],
    thumbnail: "webnovel_13.webp",
  },
  {
    id: 133,
    title: "왕국의 연인",
    author: ["하늘"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 280000,
    rating: 8.5,
    description: "왕국의 금지된 사랑 이야기.",
    keywords: ["로판", "왕국"],
    thumbnail: "webnovel_14.webp",
  },
  {
    id: 134,
    title: "황녀의 비밀",
    author: ["민아"],
    main: "webnovel",
    sub: "romance-fantasy",
    views: 270000,
    rating: 8.4,
    description: "황녀의 비밀스러운 사랑 이야기.",
    keywords: ["로판", "비밀"],
    thumbnail: "webnovel_16.webp",
  },
  {
    id: 135,
    title: "마나 없는 마법사",
    author: ["하린"],
    main: "webnovel",
    sub: "fantasy",
    views: 280000,
    rating: 8.9,
    description: "마나 없이 지식으로 성장하는 마법사.",
    keywords: ["판타지", "마법"],
    thumbnail: "webnovel_11.jpg",
  },
  {
    id: 136,
    title: "제국의 기사",
    author: ["도현"],
    main: "webnovel",
    sub: "fantasy",
    views: 260000,
    rating: 8.8,
    description: "제국의 마지막 기사가 다시 일어선다.",
    keywords: ["판타지", "기사"],
    thumbnail: "webnovel_15.jpg",
  },
  {
    id: 137,
    title: "탑에 오르다",
    author: ["잠자는 또끼"],
    main: "webnovel",
    sub: "fantasy",
    views: 250000,
    rating: 8.7,
    description: "세상에 나타난 탑에 오르다.",
    keywords: ["판타지", "탑"],
    thumbnail: "webnovel_19.jpg",
  },
  {
    id: 138,
    title: "던전 푸드 트럭 요리사",
    author: ["아리엔"],
    main: "webnovel",
    sub: "fantasy",
    views: 240000,
    rating: 8.8,
    description: "던전에서 푸드 트럭에서 장사하다!",
    keywords: ["판타지", "던전"],
    thumbnail: "webnovel_13.webp",
  },
  {
    id: 139,
    title: "랭커 회귀",
    author: ["잠자는 토끼"],
    main: "webnovel",
    sub: "fantasy",
    views: 230000,
    rating: 8.7,
    description: "게임 랭커가 회귀하여 다시 시작한다.",
    keywords: ["판타지", "회귀"],
    thumbnail: "webnovel_16.webp",
  },
];

export default contents;
