import React from "react";
import S from "./style";
import { Link } from "react-router-dom";
import MainBanner from "./MainBanner";
import ContentCard from "./ContentCard";

const MainContainer = () => {
  const mainBanner = [
    //웹툰
    {
      id: 1,
      main: "webtoon",
      sub: "recommend",
      title: "jbook 웹툰 신간 출시",
      slug: "/webtoon/recommend",
      img: "main_banner_01.webp",
    },
    {
      id: 2,
      main: "webnovel",
      sub: "recommend",
      title: "jbook 웹소설 신간 출시",
      slug: "/webnovel/recommend",
      img: "main_banner_01.webp",
    },
    {
      id: 3,
      main: "ebook",
      sub: "recommend",
      title: "jbook 도서 신간 출시",
      slug: "/ebook/recommend",
      img: "main_banner_01.webp",
    },
    {
      id: 4,
      main: "webtoon",
      sub: "recommend",
      title: "jbook 웹툰 신간 출시2",
      slug: "/webtoon/recommend",
      img: "main_banner_01.webp",
    },
  ];

  const contents = [
    {
      id: 1,
      title: "환생자의 스트리밍",
      author: ["넥스트레벨스튜디오", "흑아인"],
      main: "webtoon",
      sub: "fantasy",
      views: 3317000,
      rating: 9.7,
      day: "sun",
      description: "죽음을 맞이한 헌터가 환생 후 스트리머로 성장하는 이야기.",
      keywords: ["환생", "헌터", "스트리밍"],
      thumbnail: "webtoon_01.webp",
    },
    {
      id: 2,
      title: "악녀의 로맨스는 없다",
      author: ["라엘"],
      main: "webtoon",
      sub: "romance",
      views: 2100000,
      rating: 9.4,
      day: "wed",
      description: "악녀로 빙의했지만 로맨스 대신 자유를 선택한 그녀.",
      keywords: ["로맨스", "빙의"],
      thumbnail: "webtoon_02.jpg",
    },
    {
      id: 3,
      title: "무림에서 온 전학생",
      author: ["천무"],
      main: "webtoon",
      sub: "murim",
      views: 1200000,
      rating: 9.2,
      day: "fri",
      description: "무림 고수가 현대 학교에 전학 오며 벌어지는 이야기.",
      keywords: ["무협", "학원"],
      thumbnail: "webtoon_03.webp",
    },
    {
      id: 4,
      title: "도시의 헌터",
      author: ["박현"],
      main: "webtoon",
      sub: "action",
      views: 980000,
      rating: 9.0,
      day: "thu",
      description: "도시를 위협하는 괴물을 사냥하는 헌터들의 이야기.",
      keywords: ["액션", "헌터"],
      thumbnail: "webtoon_04.webp",
    },
    {
      id: 5,
      title: "귀신 보는 탐정",
      author: ["서윤"],
      main: "webtoon",
      sub: "horror-mystery",
      views: 760000,
      rating: 8.8,
      day: "sat",
      description: "귀신을 볼 수 있는 탐정의 미스터리 사건 해결기.",
      keywords: ["공포", "추리"],
      thumbnail: "webtoon_05.jpg",
    },
    {
      id: 6,
      title: "우리들의 계절",
      author: ["김다은"],
      main: "webtoon",
      sub: "drama",
      views: 640000,
      rating: 8.9,
      day: "mon",
      description: "청춘들의 우정과 사랑을 그린 성장 드라마.",
      keywords: ["드라마", "청춘"],
      thumbnail: "webtoon_06.png",
    },
    {
      id: 7,
      title: "은하계 기사단",
      author: ["이준"],
      main: "webtoon",
      sub: "fantasy",
      views: 880000,
      rating: 9.1,
      day: "tue",
      description: "우주를 지키는 기사단의 SF 판타지 모험.",
      keywords: ["SF", "우주"],
      thumbnail: "webtoon_07.webp",
    },
    {
      id: 8,
      title: "첫사랑 알고리즘",
      author: ["한서"],
      main: "webtoon",
      sub: "romance",
      views: 720000,
      rating: 8.7,
      day: "sun",
      description: "AI로 사랑을 분석하려는 대학생들의 이야기.",
      keywords: ["로맨스", "캠퍼스"],
      thumbnail: "webtoon_08.webp",
    },

    // 웹소설
    {
      id: 9,
      title: "황녀의 계약 결혼",
      author: ["리아"],
      main: "webnovel",
      sub: "romance-fantasy",
      views: 2300000,
      rating: 9.6,
      day: null,
      description: "몰락한 황녀와 공작의 계약 결혼 이야기.",
      keywords: ["로판", "계약결혼"],
      thumbnail: "webnovel_01.webp",
    },
    {
      id: 10,
      title: "마나 없는 마법사",
      author: ["하린"],
      main: "webnovel",
      sub: "fantasy",
      views: 870000,
      rating: 9.0,
      day: null,
      description: "마나 없이 지식으로 성장하는 마법사.",
      keywords: ["판타지", "성장"],
      thumbnail: "webnovel_02.webp",
    },
    {
      id: 11,
      title: "그녀의 비밀 연애",
      author: ["소라"],
      main: "webnovel",
      sub: "romance",
      views: 920000,
      rating: 9.2,
      day: null,
      description: "평범한 직장인의 비밀스러운 로맨스.",
      keywords: ["로맨스", "직장"],
      thumbnail: "webnovel_03.jpg",
    },
    {
      id: 12,
      title: "제국의 마지막 기사",
      author: ["도현"],
      main: "webnovel",
      sub: "fantasy",
      views: 680000,
      rating: 8.9,
      day: null,
      description: "멸망한 제국의 마지막 기사가 다시 일어선다.",
      keywords: ["기사", "전쟁"],
      thumbnail: "webnovel_04.jpg",
    },
    {
      id: 13,
      title: "악녀는 오늘도 바쁘다",
      author: ["엘린"],
      main: "webnovel",
      sub: "romance-fantasy",
      views: 1100000,
      rating: 9.3,
      day: null,
      description: "악녀로 환생했지만 사업가로 성공하려는 이야기.",
      keywords: ["로판", "환생"],
      thumbnail: "webnovel_05.jpg",
    },
    {
      id: 14,
      title: "랭커가 되었더니 회귀하다.",
      author: ["잠자는 토끼"],
      main: "webnovel",
      sub: "fantasy",
      views: 200000,
      rating: 9.0,
      description: "드디어 게임 랭커가 된 그 순간 레벨 1로 회귀하다.",
      keywords: ["판타지", "회귀", "게임"],
      thumbnail: "webnovel_06.png",
    },
    {
      id: 15,
      title: "탑에 오르다",
      author: ["잠자는 또끼"],
      main: "webnovel",
      sub: "fantasy",
      views: 150000,
      rating: 8.7,
      description: "세상에 나타난 탑에 오르다",
      keywords: ["판타지", "아포칼립스", "던전"],
      thumbnail: "webnovel_07.jpb",
    },
    {
      id: 16,
      title: "던전 요리사",
      author: ["아리엔"],
      main: "webnovel",
      sub: "fantasy",
      views: 180000,
      rating: 8.8,
      description: "던전 요리사로 각성!! 유일무일 던전 요리사가 되다.",
      keywords: ["판타지", "던전"],
      thumbnail: "webnovel_08.jpg",
    },

    // 도서
    {
      id: 15,
      title: "인류의 역사",
      author: ["이정훈"],
      main: "ebook",
      sub: "humanities-social-history",
      views: 150000,
      rating: 8.7,
      description: "인류 문명의 흐름을 쉽게 설명한 역사 교양서.",
      keywords: ["역사"],
      thumbnail: "ebook_01.webp",
    },
    {
      id: 16,
      title: "성공하는 습관",
      author: ["박성민"],
      main: "ebook",
      sub: "self-development",
      views: 180000,
      rating: 8.8,
      description: "성공한 사람들의 습관을 분석한 자기계발서.",
      keywords: ["습관"],
      thumbnail: "ebook_02.webp",
    },
    {
      id: 17,
      title: "경영의 기술",
      author: ["최강"],
      main: "ebook",
      sub: "business-economy",
      views: 120000,
      rating: 8.5,
      description: "현대 기업 경영 전략을 설명한 책.",
      keywords: ["경영"],
      thumbnail: "ebook_03.webp",
    },
    {
      id: 18,
      title: "조용한 시",
      author: ["김하늘"],
      main: "ebook",
      sub: "essay-poetry",
      views: 80000,
      rating: 8.6,
      description: "삶의 감정을 담은 시와 에세이 모음.",
      keywords: ["에세이", "시"],
      thumbnail: "ebook_04.jpg",
    },
    {
      id: 19,
      title: "도시의 철학",
      author: ["이상우"],
      main: "ebook",
      sub: "humanities-social-history",
      views: 90000,
      rating: 8.4,
      description: "도시 속 인간의 삶을 철학적으로 탐구한다.",
      keywords: ["철학"],
      thumbnail: "ebook_05.jpg",
    },
    {
      id: 20,
      title: "문학의 순간",
      author: ["정유진"],
      main: "ebook",
      sub: "novel",
      views: 130000,
      rating: 8.7,
      description: "인간 관계와 삶을 그린 현대 소설.",
      keywords: ["소설"],
      thumbnail: "ebook_06.webp",
    },
    {
      id: 21,
      title: "별이 빛나는 밤에",
      author: ["김하늘"],
      main: "ebook",
      sub: "novel",
      views: 98000,
      rating: 8.5,
      description: "청춘의 고민과 사랑을 담은 감성적인 성장 소설.",
      keywords: ["소설", "청춘", "성장"],
      thumbnail: "ebook_07.webp",
    },
    {
      id: 22,
      title: "시간의 서재",
      author: ["박민준"],
      main: "ebook",
      sub: "novel",
      views: 112000,
      rating: 9.0,
      description: "오래된 도서관에서 펼쳐지는 미스터리한 이야기.",
      keywords: ["미스터리", "소설"],
      thumbnail: "ebook_08.webp",
    },
  ];

  return (
    <div>
      <MainBanner mainBanner={mainBanner} />
      <div>
        <ContentCard contents={contents} />
      </div>
      <div>
        <ContentCard contents={contents} />
      </div>
      <div>
        <ContentCard contents={contents} />
      </div>
    </div>
  );
};

export default MainContainer;
