import React from "react";
import S from "./style";
import { Link, useParams } from "react-router-dom";
import MainBanner from "./MainBanner";
import ContentCard from "./ContentCard";

const MainContainer = () => {
  const mainBanner = [
    //웹툰
    {
      id: 1,
      main: "webtoon",
      sub: "recommend",
      title: "jbook 웹툰 신간 출시",
      slug: "/webtoon/recommend",
      img: "main_banner_01.webp",
    },
    {
      id: 2,
      main: "webnovel",
      sub: "recommend",
      title: "jbook 웹소설 신간 출시",
      slug: "/webnovel/recommend",
      img: "main_banner_01.webp",
    },
    {
      id: 3,
      main: "ebook",
      sub: "recommend",
      title: "jbook 도서 신간 출시",
      slug: "/ebook/recommend",
      img: "main_banner_01.webp",
    },
    {
      id: 4,
      main: "webtoon",
      sub: "recommend",
      title: "jbook 웹툰 신간 출시2",
      slug: "/webtoon/recommend",
      img: "main_banner_01.webp",
    },
  ];

  const contents = [
    {
      id: 1,
      title: "환생자의 스트리밍",
      author: ["넥스트레벨스튜디오", "흑아인"],
      main: "webtoon",
      sub: "fantasy",
      views: 3317000,
      rating: 9.7,
      day: "sun",
      description: "죽음을 맞이한 헌터가 환생 후 스트리머로 성장하는 이야기.",
      keywords: ["환생", "헌터", "스트리밍"],
      thumbnail: "webtoon_01.webp",
    },
    {
      id: 2,
      title: "악녀의 로맨스는 없다",
      author: ["라엘"],
      main: "webtoon",
      sub: "romance",
      views: 2100000,
      rating: 9.4,
      day: "wed",
      description: "악녀로 빙의했지만 로맨스 대신 자유를 선택한 그녀.",
      keywords: ["로맨스", "빙의"],
      thumbnail: "webtoon_02.jpg",
    },
    {
      id: 3,
      title: "무림에서 온 전학생",
      author: ["천무"],
      main: "webtoon",
      sub: "murim",
      views: 1200000,
      rating: 9.2,
      day: "fri",
      description: "무림 고수가 현대 학교에 전학 오며 벌어지는 이야기.",
      keywords: ["무협", "학원"],
      thumbnail: "webtoon_03.webp",
    },
    {
      id: 4,
      title: "도시의 헌터",
      author: ["박현"],
      main: "webtoon",
      sub: "action",
      views: 980000,
      rating: 9.0,
      day: "thu",
      description: "도시를 위협하는 괴물을 사냥하는 헌터들의 이야기.",
      keywords: ["액션", "헌터"],
      thumbnail: "webtoon_04.webp",
    },
    {
      id: 5,
      title: "귀신 보는 탐정",
      author: ["서윤"],
      main: "webtoon",
      sub: "horror-mystery",
      views: 760000,
      rating: 8.8,
      day: "sat",
      description: "귀신을 볼 수 있는 탐정의 미스터리 사건 해결기.",
      keywords: ["공포", "추리"],
      thumbnail: "webtoon_05.jpg",
    },
    {
      id: 6,
      title: "우리들의 계절",
      author: ["김다은"],
      main: "webtoon",
      sub: "drama",
      views: 640000,
      rating: 8.9,
      day: "mon",
      description: "청춘들의 우정과 사랑을 그린 성장 드라마.",
      keywords: ["드라마", "청춘"],
      thumbnail: "webtoon_06.png",
    },
    {
      id: 7,
      title: "은하계 기사단",
      author: ["이준"],
      main: "webtoon",
      sub: "fantasy",
      views: 880000,
      rating: 9.1,
      day: "tue",
      description: "우주를 지키는 기사단의 SF 판타지 모험.",
      keywords: ["SF", "우주"],
      thumbnail: "webtoon_07.webp",
    },
    {
      id: 8,
      title: "첫사랑 알고리즘",
      author: ["한서"],
      main: "webtoon",
      sub: "romance",
      views: 720000,
      rating: 8.7,
      day: "sun",
      description: "AI로 사랑을 분석하려는 대학생들의 이야기.",
      keywords: ["로맨스", "캠퍼스"],
      thumbnail: "webtoon_08.webp",
    },

    // 웹소설
    {
      id: 9,
      title: "황녀의 계약 결혼",
      author: ["리아"],
      main: "webnovel",
      sub: "romance-fantasy",
      views: 2300000,
      rating: 9.6,
      day: null,
      description: "몰락한 황녀와 공작의 계약 결혼 이야기.",
      keywords: ["로판", "계약결혼"],
      thumbnail: "webnovel_01.webp",
    },
    {
      id: 10,
      title: "마나 없는 마법사",
      author: ["하린"],
      main: "webnovel",
      sub: "fantasy",
      views: 870000,
      rating: 9.0,
      day: null,
      description: "마나 없이 지식으로 성장하는 마법사.",
      keywords: ["판타지", "성장"],
      thumbnail: "webnovel_02.webp",
    },
    {
      id: 11,
      title: "그녀의 비밀 연애",
      author: ["소라"],
      main: "webnovel",
      sub: "romance",
      views: 920000,
      rating: 9.2,
      day: null,
      description: "평범한 직장인의 비밀스러운 로맨스.",
      keywords: ["로맨스", "직장"],
      thumbnail: "webnovel_03.jpg",
    },
    {
      id: 12,
      title: "제국의 마지막 기사",
      author: ["도현"],
      main: "webnovel",
      sub: "fantasy",
      views: 680000,
      rating: 8.9,
      day: null,
      description: "멸망한 제국의 마지막 기사가 다시 일어선다.",
      keywords: ["기사", "전쟁"],
      thumbnail: "webnovel_04.jpg",
    },
    {
      id: 13,
      title: "악녀는 오늘도 바쁘다",
      author: ["엘린"],
      main: "webnovel",
      sub: "romance-fantasy",
      views: 1100000,
      rating: 9.3,
      day: null,
      description: "악녀로 환생했지만 사업가로 성공하려는 이야기.",
      keywords: ["로판", "환생"],
      thumbnail: "webnovel_05.jpg",
    },
    {
      id: 14,
      title: "랭커가 되었더니 회귀하다.",
      author: ["잠자는 토끼"],
      main: "webnovel",
      sub: "fantasy",
      views: 200000,
      rating: 9.0,
      description: "드디어 게임 랭커가 된 그 순간 레벨 1로 회귀하다.",
      keywords: ["판타지", "회귀", "게임"],
      thumbnail: "webnovel_06.png",
    },
    {
      id: 15,
      title: "탑에 오르다",
      author: ["잠자는 또끼"],
      main: "webnovel",
      sub: "fantasy",
      views: 150000,
      rating: 8.7,
      description: "세상에 나타난 탑에 오르다",
      keywords: ["판타지", "아포칼립스", "던전"],
      thumbnail: "webnovel_07.jpg",
    },
    {
      id: 16,
      title: "던전 요리사",
      author: ["아리엔"],
      main: "webnovel",
      sub: "fantasy",
      views: 180000,
      rating: 8.8,
      description: "던전 요리사로 각성!! 유일무일 던전 요리사가 되다.",
      keywords: ["판타지", "던전"],
      thumbnail: "webnovel_08.jpg",
    },

    // 도서
    {
      id: 17,
      title: "인류의 역사",
      author: ["이정훈"],
      main: "ebook",
      sub: "humanities-social-history",
      views: 150000,
      rating: 8.7,
      description: "인류 문명의 흐름을 쉽게 설명한 역사 교양서.",
      keywords: ["역사"],
      thumbnail: "ebook_01.webp",
    },
    {
      id: 18,
      title: "성공하는 습관",
      author: ["박성민"],
      main: "ebook",
      sub: "self-development",
      views: 180000,
      rating: 8.8,
      description: "성공한 사람들의 습관을 분석한 자기계발서.",
      keywords: ["습관"],
      thumbnail: "ebook_02.webp",
    },
    {
      id: 19,
      title: "경영의 기술",
      author: ["최강"],
      main: "ebook",
      sub: "business-economy",
      views: 120000,
      rating: 8.5,
      description: "현대 기업 경영 전략을 설명한 책.",
      keywords: ["경영"],
      thumbnail: "ebook_03.webp",
    },
    {
      id: 20,
      title: "조용한 시",
      author: ["김하늘"],
      main: "ebook",
      sub: "essay-poetry",
      views: 80000,
      rating: 8.6,
      description: "삶의 감정을 담은 시와 에세이 모음.",
      keywords: ["에세이", "시"],
      thumbnail: "ebook_04.jpg",
    },
    {
      id: 21,
      title: "도시의 철학",
      author: ["이상우"],
      main: "ebook",
      sub: "humanities-social-history",
      views: 90000,
      rating: 8.4,
      description: "도시 속 인간의 삶을 철학적으로 탐구한다.",
      keywords: ["철학"],
      thumbnail: "ebook_05.jpg",
    },
    {
      id: 22,
      title: "문학의 순간",
      author: ["정유진"],
      main: "ebook",
      sub: "novel",
      views: 130000,
      rating: 8.7,
      description: "인간 관계와 삶을 그린 현대 소설.",
      keywords: ["소설"],
      thumbnail: "ebook_06.webp",
    },
    {
      id: 23,
      title: "별이 빛나는 밤에",
      author: ["김하늘"],
      main: "ebook",
      sub: "novel",
      views: 98000,
      rating: 8.5,
      description: "청춘의 고민과 사랑을 담은 감성적인 성장 소설.",
      keywords: ["소설", "청춘", "성장"],
      thumbnail: "ebook_07.webp",
    },
    {
      id: 24,
      title: "시간의 서재",
      author: ["박민준"],
      main: "ebook",
      sub: "novel",
      views: 112000,
      rating: 9.0,
      description: "오래된 도서관에서 펼쳐지는 미스터리한 이야기.",
      keywords: ["미스터리", "소설"],
      thumbnail: "ebook_08.webp",
    },
    {
      id: 25,
      title: "검왕의 귀환",
      author: ["강태성"],
      main: "webtoon",
      sub: "murim",
      views: 540000,
      rating: 9.1,
      day: "mon",
      description: "전설의 검왕이 현대에 다시 돌아왔다.",
      keywords: ["무협", "환생"],
      thumbnail: "webtoon_09.webp",
    },
    {
      id: 26,
      title: "AI 연인",
      author: ["유리"],
      main: "webtoon",
      sub: "romance",
      views: 430000,
      rating: 8.8,
      day: "tue",
      description: "AI와 사랑에 빠진 개발자의 이야기.",
      keywords: ["로맨스", "AI"],
      thumbnail: "webtoon_10.webp",
    },
    {
      id: 27,
      title: "아포칼립스 생존자",
      author: ["정민"],
      main: "webtoon",
      sub: "action",
      views: 620000,
      rating: 9.0,
      day: "fri",
      description: "멸망한 세상에서 살아남은 사람들의 이야기.",
      keywords: ["액션", "아포칼립스"],
      thumbnail: "webtoon_01.webp",
    },
    {
      id: 28,
      title: "마왕의 딸",
      author: ["엘라"],
      main: "webtoon",
      sub: "fantasy",
      views: 700000,
      rating: 9.3,
      day: "sun",
      description: "마왕의 딸이 인간 세계에서 살아가는 이야기.",
      keywords: ["판타지", "마왕"],
      thumbnail: "webtoon_03.webp",
    },
    {
      id: 29,
      title: "도시 괴담 수집가",
      author: ["이도"],
      main: "webtoon",
      sub: "horror-mystery",
      views: 380000,
      rating: 8.6,
      day: "sat",
      description: "도시 괴담을 수집하는 기자의 이야기.",
      keywords: ["공포", "괴담"],
      thumbnail: "webtoon_04.webp",
    },
    {
      id: 30,
      title: "황제의 숨겨진 후계자",
      author: ["카린"],
      main: "webnovel",
      sub: "romance-fantasy",
      views: 760000,
      rating: 9.1,
      description: "숨겨진 황제의 후계자가 궁에 들어오면서 벌어지는 이야기.",
      keywords: ["로판", "궁중"],
      thumbnail: "webnovel_09.webp",
    },
    {
      id: 31,
      title: "던전 마스터의 귀환",
      author: ["이준혁"],
      main: "webnovel",
      sub: "fantasy",
      views: 540000,
      rating: 8.9,
      description: "던전 마스터가 다시 세상에 돌아왔다.",
      keywords: ["던전", "환생"],
      thumbnail: "webnovel_10.png",
    },
    {
      id: 32,
      title: "사랑은 알고리즘처럼",
      author: ["민서"],
      main: "webnovel",
      sub: "romance",
      views: 420000,
      rating: 8.7,
      description: "완벽한 사랑을 찾는 데이터 분석가의 이야기.",
      keywords: ["로맨스", "연애"],
      thumbnail: "webnovel_01.webp",
    },
    {
      id: 33,
      title: "왕국의 마법사",
      author: ["도윤"],
      main: "webnovel",
      sub: "fantasy",
      views: 390000,
      rating: 8.8,
      description: "왕국을 지키는 젊은 마법사의 성장기.",
      keywords: ["마법", "성장"],
      thumbnail: "webnovel_03.jpg",
    },
    {
      id: 34,
      title: "악역은 오늘도 살아남는다",
      author: ["리아나"],
      main: "webnovel",
      sub: "romance-fantasy",
      views: 610000,
      rating: 9.2,
      description: "소설 속 악역으로 빙의한 여자의 생존기.",
      keywords: ["빙의", "로판"],
      thumbnail: "webnovel_08.jpg",
    },
    {
      id: 35,
      title: "철학자의 하루",
      author: ["박준"],
      main: "ebook",
      sub: "humanities-social-history",
      views: 45000,
      rating: 8.5,
      description: "철학자의 시선으로 바라본 하루의 의미.",
      keywords: ["철학"],
      thumbnail: "ebook_09.png",
    },
    {
      id: 36,
      title: "경제의 흐름",
      author: ["김민수"],
      main: "ebook",
      sub: "business-economy",
      views: 72000,
      rating: 8.6,
      description: "현대 경제의 흐름을 쉽게 설명한다.",
      keywords: ["경제"],
      thumbnail: "ebook_10.webp",
    },
    {
      id: 37,
      title: "마음의 기록",
      author: ["이서연"],
      main: "ebook",
      sub: "essay-poetry",
      views: 38000,
      rating: 8.4,
      description: "삶의 감정을 기록한 에세이 모음.",
      keywords: ["에세이"],
      thumbnail: "ebook_01.webp",
    },
    {
      id: 38,
      title: "성장의 기술",
      author: ["정우"],
      main: "ebook",
      sub: "self-development",
      views: 91000,
      rating: 8.9,
      description: "자기 성장을 위한 실천 전략.",
      keywords: ["자기계발"],
      thumbnail: "ebook_04.jpg",
    },
    {
      id: 39,
      title: "밤의 도서관",
      author: ["김하늘"],
      main: "ebook",
      sub: "novel",
      views: 56000,
      rating: 8.7,
      description: "밤이 되면 살아나는 도서관 이야기.",
      keywords: ["소설", "미스터리"],
      thumbnail: "ebook_03.webp",
    },
    {
      id: 40,
      title: "사라진 왕국",
      author: ["최민"],
      main: "ebook",
      sub: "novel",
      views: 62000,
      rating: 8.6,
      description: "사라진 왕국의 비밀을 찾는 모험 소설.",
      keywords: ["모험", "소설"],
      thumbnail: "ebook_06.webp",
    },
    {
      id: 41,
      title: "세계사 산책",
      author: ["이정훈"],
      main: "ebook",
      sub: "humanities-social-history",
      views: 84000,
      rating: 8.8,
      description: "세계사를 흥미롭게 풀어낸 역사 교양서.",
      keywords: ["세계사"],
      thumbnail: "ebook_07.webp",
    },
    {
      id: 42,
      title: "부자의 사고방식",
      author: ["김도현"],
      main: "ebook",
      sub: "business-economy",
      views: 97000,
      rating: 9.0,
      description: "성공한 사람들의 사고방식을 분석한다.",
      keywords: ["경제", "성공"],
      thumbnail: "ebook_08.webp",
    },
    {
      id: 43,
      title: "감정의 온도",
      author: ["서지안"],
      main: "ebook",
      sub: "essay-poetry",
      views: 41000,
      rating: 8.5,
      description: "일상 속 감정을 담은 에세이.",
      keywords: ["감정", "에세이"],
      thumbnail: "ebook_10.webp",
    },
    {
      id: 44,
      title: "내일을 준비하는 법",
      author: ["이수진"],
      main: "ebook",
      sub: "self-development",
      views: 66000,
      rating: 8.8,
      description: "미래를 준비하는 사람들을 위한 자기계발서.",
      keywords: ["자기계발"],
      thumbnail: "ebook_01.webp",
    },
    {
      id: 45,
      title: "던전 청소부",
      author: ["김태훈"],
      main: "webtoon",
      sub: "action",
      views: 420000,
      rating: 8.9,
      day: "mon",
      description: "던전이 끝난 뒤 몬스터 잔해를 치우는 청소부의 이야기.",
      keywords: ["던전", "헌터"],
      thumbnail: "webtoon_08.webp",
    },
    {
      id: 46,
      title: "마법학교 낙제생",
      author: ["한지우"],
      main: "webtoon",
      sub: "fantasy",
      views: 510000,
      rating: 9.0,
      day: "tue",
      description: "마법을 못 쓰는 학생이 마법학교에서 살아남는 이야기.",
      keywords: ["마법", "학원"],
      thumbnail: "webtoon_09.webp",
    },
    {
      id: 47,
      title: "그녀의 이중생활",
      author: ["서연"],
      main: "webtoon",
      sub: "drama",
      views: 370000,
      rating: 8.7,
      day: "wed",
      description: "낮에는 회사원, 밤에는 인기 스트리머인 그녀의 이야기.",
      keywords: ["드라마", "일상"],
      thumbnail: "webtoon_10.webp",
    },
    {
      id: 48,
      title: "첫사랑 리셋",
      author: ["이민재"],
      main: "webtoon",
      sub: "romance",
      views: 600000,
      rating: 9.2,
      day: "thu",
      description: "첫사랑과 다시 만난 두 사람의 리셋된 로맨스.",
      keywords: ["로맨스", "재회"],
      thumbnail: "webtoon_04.webp",
    },
    {
      id: 49,
      title: "귀신 아파트",
      author: ["박소영"],
      main: "webtoon",
      sub: "horror-mystery",
      views: 330000,
      rating: 8.5,
      day: "fri",
      description: "귀신이 산다는 아파트에서 벌어지는 미스터리.",
      keywords: ["공포", "괴담"],
      thumbnail: "webtoon_08.webp",
    },
    {
      id: 50,
      title: "무림 편의점",
      author: ["천무"],
      main: "webtoon",
      sub: "murim",
      views: 470000,
      rating: 9.1,
      day: "sat",
      description: "무림 고수들이 찾는 특별한 편의점 이야기.",
      keywords: ["무협", "코믹"],
      thumbnail: "webtoon_02.jpg",
    },
    {
      id: 51,
      title: "우주 택배",
      author: ["정하늘"],
      main: "webtoon",
      sub: "fantasy",
      views: 390000,
      rating: 8.8,
      day: "sun",
      description: "우주를 누비는 택배기사의 SF 모험.",
      keywords: ["SF", "모험"],
      thumbnail: "webtoon_06.png",
    },
    {
      id: 52,
      title: "연애 시뮬레이션",
      author: ["김지훈"],
      main: "webtoon",
      sub: "romance",
      views: 450000,
      rating: 8.9,
      day: "mon",
      description: "게임처럼 연애를 분석하는 대학생들의 이야기.",
      keywords: ["로맨스", "캠퍼스"],
      thumbnail: "webtoon_03.webp",
    },
    {
      id: 53,
      title: "헌터 랭킹 1위",
      author: ["이강"],
      main: "webtoon",
      sub: "action",
      views: 680000,
      rating: 9.3,
      day: "wed",
      description: "세계 최고의 헌터가 되는 과정을 그린 액션 웹툰.",
      keywords: ["헌터", "액션"],
      thumbnail: "webtoon_06.png",
    },
    {
      id: 54,
      title: "시간을 걷는 소녀",
      author: ["최윤"],
      main: "webtoon",
      sub: "drama",
      views: 310000,
      rating: 8.6,
      day: "thu",
      description: "시간을 되돌릴 수 있는 소녀의 성장 이야기.",
      keywords: ["시간", "성장"],
      thumbnail: "webtoon_05.jpg",
    },
  ];
  const {main} = useParams()

  return (
    <div>
      {main === "daily" ? <></> : (<MainBanner mainBanner={mainBanner} />)}
      <div>
        <ContentCard contents={contents} />
      </div>
    </div>
  );
};

export default MainContainer;
